clientes:
    resource: "@ClientesBundle/Controller/"
    type:     annotation
    prefix:   /

productos:
    resource: "@ProductosBundle/Controller/"
    type:     annotation
    prefix:   /

facturas:
    resource: "@FacturasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
