<?php

namespace ClientesBundle\Repository;

/**
 * clientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientesRepository extends \Doctrine\ORM\EntityRepository
{
}
