<?php

namespace FacturasBundle\Repository;

/**
 * facturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class facturasRepository extends \Doctrine\ORM\EntityRepository
{
}
